### ISSUE TITLE
Listener restart error

### ISSUE THREAD

**Issue by fiersik** [MalpenZibo/ashell#57]
When turning off the monitors, an error appears after turning them back on
```
ERROR [ashell::modules::title] restarting active window listener due to error: Internal("MonitorAddedV2: invalid integer error: invalid digit found in string")
ERROR [ashell::modules::workspaces] restarting workspaces listener due to error: Internal("MonitorAddedV2: invalid integer error: invalid digit found in string")
```

After that, the panel stops being displayed

**Comment by MalpenZibo** [comment]
With panel do you mean the entire status bar? Does the `ashell` process still run?

**Comment by fiersik** [comment]
Yes, I mean the entire status bar, the process remains in a semi-started state.
the process is not displayed in htop, it cannot be killed using pkill, but it is also impossible to start a new one

```
 ~  WGPU_BACKEND=gl ashell
INFO [ashell::config] Reading config file
ERROR [ashell] Panic: panicked at alloc/src/raw_vec.rs:24:5:
capacity overflow
```

**Comment by MalpenZibo** [comment]
Hum, you are using a desktop PC? I only have a laptop so I'm not sure if I can replicate this behavior.

**Comment by fiersik** [comment]
> Hum, you are using a desktop PC?

Yes

> I only have a laptop so I'm not sure if I can replicate this behavior.

Most likely it will happen again when you close the laptop lid

**Comment by MalpenZibo** [comment]
I already tried. I'm using `ashell` on my working laptop daily, and this issue never happens to me. Something similar happens (a crash) only when I use an external monitor with an adaptor USB-C -> HDMI. Until now I didn't discover the root cause of that problem.

**Comment by fiersik** [comment]
The strangest thing here is not even that it crashes with an error.

when you turn off the monitors, hyprland stops some processes, for example, waybar also crashes when the monitor is turned off.

the strangest thing is that it doesn't work to restart ashell after that, only restarting the PC helps

**Comment by IceDBorn** [comment]
@fiersik This does not happen to me with waybar.

**Comment by fiersik** [comment]
> @fiersik This does not happen to me with waybar.

This started happening after switching to aquamarine, and waybar has already fixed it.

**Comment by MalpenZibo** [comment]
It's not a fix but tomorrow I will create a PR where I place a proper log init config (using this syntax https://docs.rs/flexi_logger/latest/flexi_logger/struct.LogSpecification.html) so it's possible to specify different log level for each crate/module and the I will create a new release (0.1.5).
In theory with a `warn` log level we should already be able to see an error log from the iced toolkit or other crate for this error but anyway this change should simplify the debug phase.

I think that the `workspaces` or `title` modules are innocent. It's strange that an error there could cause the crash of the entire app. It could be something related to a change in the `wl_output` and in that case maybe this PR https://github.com/MalpenZibo/ashell/pull/35 or the one that uses the pop_os fork of iced https://github.com/MalpenZibo/ashell/pull/42 or the one that adds the multi-monitor feature could resolve this issue. 
Sadly right now I have some other problems with those PR so I cannot merge that feature

**Comment by fiersik** [comment]
The new release is great news, I will immediately assemble it under ALT and send it for testing.

But there is no hurry yet.

**Comment by fiersik** [comment]
I can't say that there is even a little more useful information in the log of the new version.
[ashell-log.txt](https://github.com/user-attachments/files/17631613/ashell-log.txt)

**Comment by fiersik** [comment]
I have an idea how to fix this, but I'm not sure about it. ,- , 

I will definitely make a Pull Request if everything works out.

**Comment by MalpenZibo** [comment]
Is this problem still relevant with the latest main branch? I have updated the iced and the hyprland-rs libraries and removed my glue layer between Wayland and iced, so maybe this problem is no longer relevant.

**Comment by fiersik** [comment]
> Is this problem still relevant with the latest main branch?

The problem is still relevant, when turning off the monitor we get this:
```
ERROR [ashell] Panic: panicked at src/modules/workspaces.rs:274:42:
error getting workspaces: workspace destroy event: TrySendError { kind: Full } 
 disabled backtrace
```

After that, the entire panel stops displaying, but judging by the log, the backend is working and monitoring all events.

**Comment by fiersik** [comment]
perhaps this is due to https://github.com/hyprwm/Hyprland/issues/7822

**Comment by romanstingler** [comment]
@fiersik do you still use ashell? and if so does this still happen to you?

@MalpenZibo I think we can close that one.
